- name: Set up zx81 emulator on pi
  hosts: raspberry
  become: yes
  become_user: pi

  tasks:
  - name: change hostname to pi-zx81
    command: raspi-config nonint do_hostname zx81-pi
    become: yes
    become_user: root

  - name: set font style
    lineinfile:
      path: /etc/default/console-setup
      search_string: 'FONTFACE=""'
      line: FONTFACE="Terminus"
    become: yes
    become_user: root

  - name: set font size
    lineinfile:
      path: /etc/default/console-setup
      search_string: 'FONTSIZE=""'
      line: FONTSIZE="16x32"
    become: yes
    become_user: root

  - name: update packages
    become: true
    become_user: root
    apt:
      upgrade: yes
      update_cache: yes
      cache_valid_time: 86400
    
  - name: install packages
    apt:
      name: 
        - xserver-xorg-input-evdev
        - matchbox-common
        - matchbox-panel 
        - matchbox-panel-manager 
        - matchbox-themes-extra 
        - matchbox-window-manager
        - libsdl1.2-dev
      state: latest
    become: true
    become_user: root

  - name: install packages no recommends
    apt:
      name:
        - xserver-xorg 
        - xserver-xorg-video-fbdev 
        - xinit 
        - pciutils 
        - xinput 
        - xfonts-100dpi 
        - xfonts-75dpi 
        - xfonts-scalable
      state: latest
      install_recommends: no
    become: true
    become_user: root

  - name: get sz81
    get_url:
      url: http://sourceforge.net/projects/sz81/files/sz81/2.1.7/sz81-2.1.7-source.tar.gz
      dest: /tmp/sz81-2.1.7-source.tar.gz
      timeout: 60

  - name: create directory
    file:
      path: /tmp/sz81-2.1.7-source
      state: directory

  - name: unzip sz81
    ansible.builtin.unarchive:
      src: /tmp/sz81-2.1.7-source.tar.gz
      dest: /tmp/sz81-2.1.7-source
      remote_src: yes
    
  #- name: Restart the system
  #  become: yes
  #  become_user: root
  #  shell: "sleep 5 && reboot"
  #  async: 1
  #  poll: 0

  - name: Wait # Wait for hosts to reboot.
    wait_for_connection: timeout=300 delay=30

  - name: Display a message
    debug: msg="Finished"
